schema-version = 1

[package]
title = "Digipal Player"
version = "1.1.0"
build-number = 2
id = "com.nexuscast.player"

[components]
[[components.interactive]]
id = "com.nexuscast.player.main"
runtime-module = "/com.amazon.kepler.keplerscript.runtime.loader_2@IKeplerScript_2_0"
launch-type = "singleton"
categories = ["com.amazon.category.main"]
